services:
  atlas:
    build: .
    container_name: atlas
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - atlas-data:/app/data
    environment:
      - ATLAS_NNTP_HOST=news.usenet.farm
      - ATLAS_NNTP_PORT=563
      - ATLAS_NNTP_USER=
      - ATLAS_NNTP_PASS=
      - ATLAS_INDEX_MODE=dynamic
      # - ATLAS_API_ENABLED=1
      # - ATLAS_API_PORT=8085
      # - ATLAS_API_KEY=
    network_mode: host

volumes:
  atlas-data:
